deploy-project:
  stage: deploy
  script:
    - rsync -arv --delete  --exclude="*.sqlite3" ./project /
    - cd /project
    - bundle install
    - rails db:migrate
    - rails db:seed
    - sv restart project
  only:
  - project